Repository inspirezonetech/TeachMeJavaScriptLikeIm5, pull requests merged in 2022-10, with the labels that each got.

#71 [tutorial] Arrow function #65
  8-functions/arrow-function.js
Labels: hacktoberfest-accepted

#68 ternary-operator tutorial
  .gitignore
  6-conditions/ternary-operator.js
Labels: hacktoberfest-accepted

#74 Update README.md
  README.md
Labels: hacktoberfest-accepted

#75 Added do-while-loop
  7-loops/do-while-loops.js
Labels: hacktoberfest-accepted, 🌟 star

#81 Added a file which states the properties and method of arrays
  3-arrays/properties_and_methods_of_arrays.js
Labels: change required before merge!

#82 Create For Each
  for-each-loop.js
Labels: change required before merge!
